from . import addtag
from . import amongus
from . import changename
from . import create
from . import help
from . import info
from . import join
from . import language
from . import leave
from . import lonely
from . import play
from . import remove
from . import removetag
from . import self